In [1]:
import pandas as pd

In [3]:
# Melt use for wide to long dataset

data = pd.DataFrame({'cse':[122,221],'ece' : [642,242], 'mech': [453,645] })

In [5]:
data

   cse  ece  mech
0  122  642   453
1  221  242   645

In [7]:
data.melt()

  variable  value
0      cse    122
1      cse    221
2      ece    642
3      ece    242
4     mech    453
5     mech    645

In [9]:
data1 = data.melt(var_name='Branch',value_name='Students_num')

In [16]:
data1

  Branch  Students_num
0    cse           122
1    cse           221
2    ece           642
3    ece           242
4   mech           453
5   mech           645

In [18]:
data_2 = pd.DataFrame({
    'Branch':['cse','ece','chem'],
    'Student':[214,324,432],
    'Specilization':['AIML','SEMI-CONDU..','ORGANIC']
})

In [21]:
data_2.melt() # want to skip branch

        variable         value
0         Branch           cse
1         Branch           ece
2         Branch          chem
3        Student           214
4        Student           324
5        Student           432
6  Specilization          AIML
7  Specilization  SEMI-CONDU..
8  Specilization       ORGANIC

In [24]:
data_2.melt(id_vars=['Branch'])

  Branch       variable         value
0    cse        Student           214
1    ece        Student           324
2   chem        Student           432
3    cse  Specilization          AIML
4    ece  Specilization  SEMI-CONDU..
5   chem  Specilization       ORGANIC