In [3]:
import pandas as pd

In [4]:
ind_tuple = [('cse',2020),('cse',2019),('cse',2022),('ece',2022),('ece',2019),('ece',2020)]
series1 = pd.Series([1,2,3,4,5,6],index=ind_tuple)

In [5]:
series1

(cse, 2020)    1
(cse, 2019)    2
(cse, 2022)    3
(ece, 2022)    4
(ece, 2019)    5
(ece, 2020)    6
dtype: int64

In [6]:
multi_idx = pd.MultiIndex.from_tuples(ind_tuple)
series2 = pd.Series([1,2,3,4,5,6],index=multi_idx)

In [7]:
series2['ece']

2022    4
2019    5
2020    6
dtype: int64

In [8]:
series2.unstack()

     2019  2020  2022
cse     2     1     3
ece     5     6     4

In [9]:
data = pd.DataFrame(
    [[1,2,3,4,5,6],
     [11,12,13,14,15,16],
     [21,22,23,24,25,26],
     [32,32,33,34,35,36]
     ],

     index=pd.MultiIndex.from_product([['ITM','BUDDHA'],['SGPA','CGPA']]),
     columns=pd.MultiIndex.from_tuples(multi_idx)
)

In [ ]:
data

             cse            ece
            2020 2019 2022 2022 2019 2020
ITM    SGPA    1    2    3    4    5    6
       CGPA   11   12   13   14   15   16
BUDDHA SGPA   21   22   23   24   25   26
       CGPA   32   32   33   34   35   36

In [ ]:
data.unstack() #use unstack function to change row into column

        cse                           ece
       2020      2019      2022      2022      2019      2020
       CGPA SGPA CGPA SGPA CGPA SGPA CGPA SGPA CGPA SGPA CGPA SGPA
BUDDHA   32   21   32   22   33   23   34   24   35   25   36   26
ITM      11    1   12    2   13    3   14    4   15    5   16    6

In [ ]:
data.unstack().stack() #use stack function to change column into row

C:\Users\Aditya\AppData\Local\Temp\ipykernel_14492\2140219495.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  data.unstack().stack()

             cse            ece
            2020 2019 2022 2022 2019 2020
BUDDHA CGPA   32   32   33   34   35   36
       SGPA   21   22   23   24   25   26
ITM    CGPA   11   12   13   14   15   16
       SGPA    1    2    3    4    5    6

In [ ]:
data.sort_index(ascending=False) #first level

             cse            ece
            2020 2019 2022 2022 2019 2020
ITM    SGPA    1    2    3    4    5    6
       CGPA   11   12   13   14   15   16
BUDDHA SGPA   21   22   23   24   25   26
       CGPA   32   32   33   34   35   36

In [ ]:
data.sort_index(level=1,ascending=False) #level second

             cse            ece
            2020 2019 2022 2022 2019 2020
ITM    SGPA    1    2    3    4    5    6
BUDDHA SGPA   21   22   23   24   25   26
ITM    CGPA   11   12   13   14   15   16
BUDDHA CGPA   32   32   33   34   35   36

In [ ]:
data.sort_index(ascending=[False,True]) # both level

             cse            ece
            2020 2019 2022 2022 2019 2020
ITM    CGPA   11   12   13   14   15   16
       SGPA    1    2    3    4    5    6
BUDDHA CGPA   32   32   33   34   35   36
       SGPA   21   22   23   24   25   26

In [15]:
data.head(1)

          cse            ece
         2020 2019 2022 2022 2019 2020
ITM SGPA    1    2    3    4    5    6

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4 entries, ('ITM', 'SGPA') to ('BUDDHA', 'CGPA')
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   (cse, 2020)  4 non-null      int64
 1   (cse, 2019)  4 non-null      int64
 2   (cse, 2022)  4 non-null      int64
 3   (ece, 2022)  4 non-null      int64
 4   (ece, 2019)  4 non-null      int64
 5   (ece, 2020)  4 non-null      int64
dtypes: int64(6)
memory usage: 480.0+ bytes

In [17]:
data.tail(1)

             cse            ece
            2020 2019 2022 2022 2019 2020
BUDDHA CGPA   32   32   33   34   35   36

In [18]:
data.transpose()

          ITM      BUDDHA
         SGPA CGPA   SGPA CGPA
cse 2020    1   11     21   32
    2019    2   12     22   32
    2022    3   13     23   33
ece 2022    4   14     24   34
    2019    5   15     25   35
    2020    6   16     26   36

In [20]:
data.swaplevel() #row swap

             cse            ece
            2020 2019 2022 2022 2019 2020
SGPA ITM       1    2    3    4    5    6
CGPA ITM      11   12   13   14   15   16
SGPA BUDDHA   21   22   23   24   25   26
CGPA BUDDHA   32   32   33   34   35   36

In [ ]:
data.swaplevel(axis=1) #column

            2020 2019 2022     2019 2020
             cse  cse  cse ece  ece  ece
ITM    SGPA    1    2    3   4    5    6
       CGPA   11   12   13  14   15   16
BUDDHA SGPA   21   22   23  24   25   26
       CGPA   32   32   33  34   35   36